package com.nizamapp.dicodingsubmission

object RaiderData {

    private val raiderName = arrayOf(
        "Double",
        "Skull",
        "Joker",
        "OOO",
        "Aqua",
        "Fourze",
        "Nadeshiko",
        "Wizard",
        "Beast",
        "Mage",
        "Gaim",
        "Knuckle",
        "Kurokage Shin",
        "Baron",
        "Drive",
        "Ex-Aid",
        "Zi-O",
        "Protodrive",
        "Cross-Z",
        "Ghost",
        "G3",
        "Chaser",
        "Kabuto",
        "Poppy",
        "Build",
        "Black",
    )

    private val raiderGender = arrayOf(
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Female",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Male",
        "Female",
        "Male",
        "Male",
    )

    private val raiderSeries = arrayOf(
        "Kamen Rider W",
        "Kamen Rider W",
        "Kamen Rider W",
        "Kamen Rider OOO",
        "Kamen Rider OOO",
        "Kamen Rider Fourze",
        "Kamen Rider Fourze",
        "Kamen Rider Wizard",
        "Kamen Rider Wizard",
        "Kamen Rider Wizard",
        "-",
        "Kamen Rider Gaim",
        "Kamen Rider Gaim",
        "Kamen Rider Baron",
        "Kamen Rider Drive",
        "Kamen Rider Ex-Aid",
        "Kamen Rider Zi-O",
        "Kamen Rider Drive",
        "Kamen Rider Build",
        "Kamen Rider Ghost",
        "Shoichi Tsugami, Kamen Rider Agito, Kamen Rider G3",
        "Kamen Rider, Roidmude Enforcer, Grim Reaper",
        "Kamen Rider Zi-O",
        "Kamen Rider Ex-Aid",
        "Kamen Rider Build",
        "-",
    )

    private val raiderMotif = arrayOf(
        "W, Modern Black Grasshopper, Joker, Detective",
        "S, Human Skull, Skull Man, Skeleton",
        "W, Modern Black Grasshopper, Joker, Detective",
        "O, Animals, Insects, Infinity, King, Medal, Slot machine",
        "Aqua: Double Riders, Water",
        "Astronaut, Rocket",
        "Spaceship, Alien, Seifuku",
        "Modern Wizard, Jewelry, Western Dragon",
        "Ancient Wizard, Lion, Chimera, Jewelry",
        "-",
        "Fruit, Samurai, Date Masamune, Shogun",
        "Walnut, Medieval Squire, Boxer",
        "Pine cone, Ashigaru",
        "Fruit, European knight",
        "Car (Drive), Racer",
        "Video Game, Gamepad, Gamer, Platform game",
        "Rolex Watch, Katakana, Heisei Kamen Riders, King, Time",
        "Protodrive: Car, Racer, Prototype\\n Mashin Chaser: Motorbike, Machine, Grim Reaper, Virus\\n Chaser: Motorbike, Racer, Machine, Vaccine, Knight, Crossing guard\\n Drive: Car,Dune buggy",
        "Cross-Z: Dragon, Music, Fire\\n Cross-Z Charge: Dragon, Fire, Jelly, Spoutbag\\n Cross-Z Magma: Magma, Dragon, Knuckle",
        "Firefly, Ghost, Eyeball, Historical figures",
        "Agito:European Dragon, Stag Beetle\\n G3: Kamen Rider Kuuga, Stag Beetle, SWAT Police, Robot Armor",
        "Protodrive: Car, Racer, Prototype\\n Mashin Chaser: Motorbike, Machine, Grim Reaper, Virus\\n Chaser: Motorbike, Racer, Machine, Vaccine, Knight, Crossing guard\\n Drive: Car,Dune buggy",
        "Stag Beetle (as Gatack), Japanese Rhinoceros Beetle (as Kabuto)",
        "Idol, Dating sim, Magical girl",
        "Biotic objects, Abiotic objects, Science, Chemistry, Industrial manufacturing",
        "Black: Southeastern Lubber Grasshopper, Sun, Demon King\\n\\nBlack RX: Green Milkweed Grasshopper, Sun, Solar Panel"
    )

    private val raiderType = arrayOf(
        "Protagonist, Hero",
        "Hero, Villain (imitated by the Dummy Dopant)",
        "Protagonist, Hero",
        "Protagonist, Hero, Anti-Hero (influenced by Purple Core Medals), Anti-Villain (Eiji Greed, formerly)",
        "Hero, Villain (Possessed by Poseidon)",
        "Protagonist, Hero",
        "Hero",
        "Protagonist, Hero",
        "Hero",
        "Apprentice, Magician (in Magic Land and Final Stage only), Support, Hero",
        "Protagonist, Hero, Villain (brainwashed, as Gaim Yami and Shocker Rider Gaim)",
        "Anti-Hero (formerly), Hero (currently), Protagonist (Gaim Gaiden: Kamen Rider Knuckle)",
        "Villain (Formerly, possessed by Kohgane), Hero (Current)",
        "Hero",
        "Protagonist, Hero (currently), Police Officer, Villain (brainwashed by Shocker, formerly)",
        "Protagonist, Hero (as Ex-Aid, currently), Anti-Hero (as Genius Gamer M), Villain (while being possessed by Parado)",
        "Protagonist, Hero (currently), Anti-Hero (undercover, temporarily in Episode 9)",
        "Villain/Anti-Villain (formerly), Hero (at first, currently), Anti-Hero (temporarily), Protagonist (Drive Saga: Kamen Rider Chaser)",
        "Hero (currently), Anti-Hero (formerly), Villain (possessed by Evolto), Protagonist (Build NEW WORLD: Kamen Rider Cross-Z)",
        "Protagonist, Hero",
        "Hero",
        "Villain/Anti-Villain (formerly), Hero (at first, currently), Anti-Hero (temporarily), Protagonist (Drive Saga: Kamen Rider Chaser)",
        "Hero",
        "Villain (brainwashed and unwillingly; formerly), Hero (currently)",
        "Protagonist, Hero, Villain (influenced by the Hazard Trigger), Villain (possessed by Evolto)",
        "Protagonist, Hero",
    )

    private val raiderEpisode = arrayOf(
        "49 (W), 2 (Wizard), 14 (Movies), 20 (Specials)",
        "3 (W), 4 (Movies), 1 (Manga), 2 (Net Movies), 1 (Stage Show)",
        "49 (W), 2 (Wizard), 14 (Movies), 20 (Specials)",
        "48 (OOO), 2 (Wizard), 4 (Zi-O), 12 (Movies), 7 (Specials)",
        "1 (movie)",
        "48 (Fourze), 2 (Wizard), 10 (Movies), 9 (Specials)",
        "2 (Movies), 1 (Novel), 1 (Net Movie), 1 (Stage Show)",
        "1 (Fourze), 53 (Wizard), 3 (Zi-O), 9 (Movie), 4 (Special)",
        "37 (Wizard), 4 (Movies), 1 (Novel), 1 (Special), 1 (Stage Show)",
        "50 (Wizard), 3 (movie)",
        "2 (Wizard), 47 (Gaim), 6 (Zi-O), 9 (Movies), 6 (Special)",
        "34 (Gaim), 3 (Movies), 1 (Novel)",
        "1 (Gaim), 1 (Movie)",
        "1 (Movie)",
        "48 (Drive), 3 (Zi-O), 8 (Movies), 4 (Type TOKUJO), 12 (Specials)",
        "1 (Ghost), 45 (Ex-Aid), 3 (Web Series), 1 (Kyuranger), 1 (Zi-O), 8 (Movies), 13 (Specials)",
        "49 (Zi-O), 4 (Movies), 4 (Specials)",
        "47 (Drive), 6 (Movies), 3 (Specials), 1 (Drama CD)",
        "49 (Build), 5 (Movies), 1 (Manga), 2 (Specials), 2 (Stage Shows)",
        "2 (Drive), 50 (Ghost), 8 (Movies), 4 (Mini-Episodes), 13 (Specials), 1 (Zyuohger)",
        "3 (Zi-O)",
        "47 (Drive), 6 (Movies), 3 (Specials), 1 (Drama CD)",
        "2 (Zi-O)",
        "45 (Ex-Aid), 12 (Wed Series), 6 (Movies), 1 (Novel), 25 (Specials), 2 (Stage Shows)",
        "48 (Build), 5 (Movies), 3 (Specials)",
        "51 (Black), 47 (RX), 3 (Decade), 10 (Movies)",
    )

    private val raiderActor = arrayOf(
        "Renn Kiriyama, Issei Kakazu (child), Yukimasa Natori (elderly), Yoshimasa Hosoya (memory of heroez)",
        "Koji Kikkawa",
        "Renn Kiriyama",
        "Shu Watanabe, Tatsuhisa Suzuki (Memory of Heroes)",
        "Atsushi Arai",
        "Sota Fukushi, Tatsuki Ishikawa (child), Kenichi Suzumura (voice in Kamen Rider Taisen)",
        "Erina Mano",
        "Shunya Shiraishi, Kaito Nakashima (child)",
        "Tasuku Nagase, Kirato Wakayama (child)",
        "Junki Tozuka",
        "Gaku Sano, Hayate Torii (child)",
        "Gaku Matsuda",
        "Saku Momose",
        "Yutaka Kobayashi",
        "Ryoma Takeuchi, Ryohei Aoki (teen)",
        "Hiroki Iijima, Rai Takahashi (child)",
        "So Okuno, Rui Takahashi (child)",
        "Taiko Katono (\"Koichi Kano\"), Daichi Endo (original,voice)",
        "Eiji Akaso",
        "Shun Nishime, Hinata Yamada (child)",
        "Toshiki Kashu",
        "Taiko Katono (\"Koichi Kano\"), Daichi Endo (original,voice)",
        "Yuki Sato",
        "Ruka Matsuda",
        "Atsuhiro Inukai, Yukiaki Kiyama (Takumi Katsuragi)",
        "Tetsuo Kurata, Ibuki (Lets Go Kamen Riders!), Hirofumi Tanaka (Voice in Super Hero Taisen), Hiroshi Kamiya (Voice in Kamen Rider Taisen (Black)), Kenichi Suzumura (Voice in Kamen Rider Taisen (Black RX))",
    )

    private val raiderDetail = arrayOf(
        "Vowing to stop anyone that makes his city cry after, as a child, witnessing Sokichi Narumi's first fight with the Spider Dopant, Shotaro eventually became Sokichi's protégé. His final job with Sokichi involved investigating a mysterious organization, at the behest of an equally mysterious client. While infiltrating a Gaia Memory research building, Shotaro met Philip for the first time. However, due to Shotaro's recklessness, their cover was blown and it indirectly led to Sokichi being shot to death. Sokichi then left Shotaro to continue on in his stead, giving Shotaro his prized fedora in his final moments. Shortly afterwards, Philip and Shotaro used the Double Driver - which Sokichi had been carrying, perhaps with the intent that he become the body of Double - to transform for the first time, in order to escape.",
        "While working as a private investigator, he was partnered with a man, similar to his protege Shotaro Hidari's partner Philip, named Seiichiro Matsui (nicknamed Matsu) and had the personal policy of never getting clients in danger. He also provided his childhood friend Fumine Sonozaki (now Shroud) refuge after she was forced to leave her family and she takes up her new identity. Sokichi gets a job to protect a friend of his and Matsu's, Melissa, who is a singer. She receives a letter from a man calling himself \"the Spider Man\" (クモ男 Kumo Otoko) , which tells her to sing a specific song. The letter goes on to say that the Spider Man will rate the song on a scale of 1-100 and for every point below 100, he will kill an audience member. After confronting Melissa's agent at the concert, the Spider Man, revealed to actually be the Spider Dopant, attacks the crowd. He gives Melissa 100 points, and no one would be killed. However, Sokichi takes the opportunity to attack the Dopant armed with only the Stag Phone. A young Shotaro is in the audience, and comments in awe of how cool Sokichi is. After returning home, Sokichi talks to Shroud, who is working on the secret hangar (which then housed the SkullGarry). Shroud offers him the Skull Memory and Lost Driver when he asked her for suggestions on how to fight the Dopants. He rejected the gift outright due to wanting to keep his humanity intact.",
        "Shotaro returns in Kamen Rider Taisen, as both Kamen Rider Double and Kamen Rider Joker. After being informed what happened in Japan, Shotaro meets with Tsukasa and Kaito, to be asked for finding someone related to Shun Aoi but refuses it due to receiving a job to search the missing pets (which Kaito claims to be idiotic). After being helped by Kaito, Tsukasa tells him about the Heisei Riders and Showa Riders beginning to fight each other and he wants Shotaro to research the reason as it is related to Shun. Soon, he is confronted by two BLACKs who think that Heisei Riders are nuisances as they attack Tsukasa when he is taking Shun to his mother. Shotaro tells Tsukasa to leave it to him as he held off the two BLACKs as Kamen Rider Joker. Kaito soon helps him as Kamen Rider Baron. In the battle, with Kaito's help, he defeats Black RX with his Rider Kick.",
        "Eiji Hino is the son of a politician who travels the world with his grandfather. During one his expeditions, he travels in Africa. During his time in Africa, Eiji attempted to use his fortune to help out a village. In turn, Eiji befriends a girl named Ruu. Following her to her village and learning the residents as well as their culture, he is dragged into a civil war between villages. During the tragic moments of the civil war, Ruu is eventually killed in the war and Eiji is held captive for ransom. His family paid for his ransom, allowing him to escape Africa; but his family then used his tragedy to gain public support for his father's political platform. Though Eiji ultimately refers to this moment as his greatest regret, the ordeal caused Eiji to lose any selfish desire and become willing to help those in need, going so far to even risking his life for complete strangers.",
        "Hailing from the 2050s (possibly 2051 when adding 40 years to 2011), Michal gained the Aqua Driver and the Aqua Miraider to fight monsters that appeared in his time, but ironically couldn't transform at first because he was afraid of water and his overall fear of being too weak to become a Rider. Receiving the Poseidon Driver from the elderly Kosei Kougami, Kougami believes that the Poseidon Driver can help Michal overcome his timidness and fear, and grant him more power. However this proved futile, and even as Poseidon, Michal couldn't win against the creatures of his time, lost, and Michal was knocked out of his transformation. Just as he was about to give up, the black hole that was created by Kiyoto Maki's death appears, and the Core Medals and Cell Medals from the past entered his body, resulting in a Greeed forming inside the Poseidon Medals. This new Greeed develops an intense desire to fight, and Michal is almost instantly overwhelmed by the new being. With Michal's personality subdued, Kamen Rider Poseidon fights in their home time period for a brief while, but after a time anomaly forms as a result of a meteor containing SOLU crashing into the ocean in the present day, the Poseidon entity sees its chance and dives through, heading off to fight the Kamen Riders of the past.",
        "After his parents died when he was in third grade, Gentaro was taken in by his grandfather Goro Kisaragi. The elder Kisaragi was a bike mechanic, and he and his grandson moved around a lot following the racing circuit (an experience Gentaro enjoyed) before moving back to the city where Gentaro initially lived with his parents.",
        "She is a mysterious girl that fell from the sky and fell into Gentaro's arms and heart during Amanogawa High School's culture festival. She is rather quiet and observant, usually only repeating only what others say. Nadeshiko had grown close and fond of Gentaro during all the time they spent together. When Zodiarts attacked and Gentaro became Kamen Rider Fourze, Nadeshiko assumed her own Rider form, which shocked Gentaro.",
        "During his childhood, Haruto's parents were badly injured during a car crash. In this event, he made a promise to keep his hope alive, saving his own life as an adolescent when he was one of the first few Gates sacrificed during a solar eclipse. Subjected to the Sabbath, pro-soccer player Haruto managed to keep his inner phantom Wizardragon, who was born in him and \"berserk\", from emerging by facing despair head-on. As a result, he obtained magical powers. Being the only one to survive the eclipse, White Wizard entrusted Koyomi to Haruto and gave him a Wizardriver and the Flame Ring. Haruto then began hunting down Phantoms as Wizard, seeking to prevent others from falling into despair and to protect his and their hope.",
        "He is a young man from the Fukui Prefecture who is rather optimistic, often believing that pinches and chances are sides of the same coin. He has a gigantic appetite and an unusual liking to mayonnaise, putting it on everything he eats, including doughnuts. He originally lived with his grandmother before he became a student archaeologist.",
        "Shunpei first met Haruto as Wizard when the Hellhound attacks him and a group of children. Afterwards, Shunpei tried to get Haruto to make him Haruto's apprentice; but he is turned down. The Hellhound took advantage of the situation by putting up the illusion that Shunpei could summon a torrent of fire. Hellhound then reveals the ruse on public television and forces Shunpei to burn the book causing him to go into despair. Wizard then appears and destroys Hellhound before going into Shunpei's mind to destroy his Inner Phantom, Cyclops. Even though Shunpei no longer has the potential to use magic, he makes himself Haruto's assistant.",
        "Kouta was born the second child of unnamed parents, however they passed away in an accident causing him to be raised by his older sister Akira Kazuraba. Throughout high school, Kouta was often \"bullied\" by Kaito Kumon due to his weak and polite demeanor that Kaito hated.",
        "Zack's past before he became a dancer was unknown. He was seen being beaten up by a few thugs before being saved by Azami. She taught him dancing and invited him to join her dance team, where her brother Peko was also a member of. Later, in 2011, Kaito Kumon took over Azami's dancing team, forming Team Baron. Zack became one of Team Baron's top dancers, and one of Kaito's most devoted followers, developing a cocky attitude in the process towards other Beat Rider teams. Gaim Gaiden: Kamen Rider Knuckle",
        "In the alternate reality created by Lapis, Peko is a soccer player at Team Baron. After the match between Team Gaim and Team Baron, Peko begins to yearn for a Driver just like Kaito and Zack, as a small grasshopper lands on his body. Later, at Team Baron's meeting place, Peko confronts Zack, claiming him to be overly arrogant. Using a Genesis Driver and a Matsubokkuri Energy Lockseed which he obtained from somewhere, he transforms into Kurokage Shin and fights Zack. Kaito, who happened to witness this, transforms into Baron and tries to stop Peko. However, Peko is suddenly overwhelmed by plants growing all over his body. As he dies, he reveals that he wanted power so that he would not be looked down upon by the other members of the team.",
        "When Drive and Gaim join forces, a replica of Kaito as a servant is created by ZZZ Megahex using data of the real Kaito Kumon collected from Kouta Kazuraba's memories. But the replica proved too much like the original as he quickly turns on Megahex on the grounds that everything the being stands for is flawed, helping the Kamen Riders battle Megahex's replica army and then holding the army of ZZZ Megahex drones so Gaim and Drive cam reach Planet Megahex and destroy the being for good. Once Megahex is destroyed, the Kaito replica shuts down like all the other replicas that Megahex created.",
        "Shinnosuke Tomari was born on December 24, 1990 to Eisuke Tomari and an unknown mother. Shinnosuke's father was a police officer who taught his son the hardships of being one. He was later suspiciously murdered in the line of duty while Shinnosuke was in middle school. This would eventually propel Shinnosuke to pursue a career in law enforcement and crack the case of his father's death.Who Can Prevent the Dark Christmas Eve? What is a Kamen Rider? Where is Chaser Going?",
        "Emu developed interests in video games at the mere age of 8, which he proved to have a natural talent for in the near future. This leads him to creating the concept for Mighty Brothers XX, to ease his loneliness. From a young age, he was a huge fan of Genm Corp. and often sent fan letters to one of its programmers, Kuroto Dan, which had included ideas for new games. Furious, but also impressed that someone could create game concepts on par with him, Kuroto sent Mighty Action C, a game in-development which, unknown to anyone but Kuroto, had been infected with a strain of the Bugster Virus, which subsequently infected the boy, birthing Parado.",
        "Sougo Tokiwa was born on April 28, 2000, as the only son of Sotaro and Namie Tokiwa. At some point in his childhood, Sougo was riding a bike at a park with his parents. He proclaims to them that he would become a king, with his teenaged-self looking back at this event during the Quartzer incident. Kamen Rider Zi-O: Over Quartzer",
        "Prior to the series, Chase was a unique Roidmude created by Krim Steinbelt that was programmed with an infallible sense of justice. His designation was labeled as Protozero (プロトゼロ Puroto Zero), with the number 000 on his number plate. Due to him being a prototype, Protozero was deactivated for a period of time. However, when the other 108 Roidmudes created by Banno were awakened, Protozero was reactivated again by Krim, now having become the Drive Driver. Protozero was thus tasked to use the Drive Driver to become Protodrive, to protect the humans and destroy the Roidmudes.\n As the first user of the Drive system, Protozero took his days as a hero seriously, focusing only on the task at hand. As Protodrive, Protozero was deployed to fight off Roidmude 005, crossing paths with Shinnosuke Tomari, who conveniently did not see him fight against the Roidmude menace. Despite Krim being upset that he and Chase could not destroy the core of a Roidmude, Protozero took the damaged Viral Core of 005 and projected his memories, learning of the Roidmude's plan to start an all out attack on humanity",
        "In 1994, 13 years before Sky Wall Incident, an unmanned space probe from Japan landed successfully on Mars and returned to Earth. After its return to the Nanba Heavy Industries Institute of Synthetic Science, the probe unexpectedly brought back an alien specimen in the form of glowing red slug-like creature, later revealed to be a portion of Evolto, deliberately sent to the probe, with the intent of finding another planet to destroy. His specimen made its way out of the probe and attempted to possess and plant itself into Yuri Banjo, a security guard who was stationed there with her husband. Instead, the specimen ended up possessing Ryuga as a fetus, causing her to fall unconscious while on duty. During a checkup at a hospital, she was discovered to be one month pregnant, which was the suspected reasoning behind her collapse.",
        "Takeru was the son of ghost hunter and Daitenku Temple owner, Ryu Tenkuji and his wife Yuri Tenkuji, who died after Takeru was born. Horrible! Disappearing World! Infinity! Power of Humanity! After the death of his father at the hands of Royal Gamma Adel, he was entrusted with the duty of a ghost hunter as Ryu passed on Miyamoto Musashi's hand guard to Takeru. He was also placed under the care of Onari, one of the Daitenku Temple's monks.",
        "In 2019, Shoichi was improving his culinary skills at a restaurant in France. As he got an emergency message, he went back to Japan when he learns that Another Agito has appeared. Because of Another Agito's power, Shoichi was linked to their whereabouts and rescued Tsukuyomi. However, he was late to realize that Another Agito’s creation was a plan by Swartz to take over his power of Agito.  2001: Awaken, the Agito!",
        "Prior to the series, Chase was a unique Roidmude created by Krim Steinbelt that was programmed with an infallible sense of justice. His designation was labeled as Protozero (プロトゼロ Puroto Zero), with the number 000 on his number plate. Due to him being a prototype, Protozero was deactivated for a period of time. However, when the other 108 Roidmudes created by Banno were awakened, Protozero was reactivated again by Krim, now having become the Drive Driver. Protozero was thus tasked to use the Drive Driver to become Protodrive, to protect the humans and destroy the Roidmudes.",
        "In 2019, Arata is still working as a member of ZECT. He's on the mission to defeat a Worm who has copied the appearance of Shun Kageyama. He encounters Sougo Tokiwa in battle with a swarm of Worms and assists him as Kamen Rider Gatack. Then, Shun appears and they fight in Clock Up mode. After Shun is knocked out by Zi-O II, Another Kabuto, who is also revealed to be So Yaguruma, intervenes and the two escapes the scene. Arata explains about ZECT and his mission to Sougo and Woz, then leaves in confusion because the supposedly destroyed Shibuya district is thriving. Some time later, Arata is lured out by Shun for Yaguruma. He battles PunchHopper as WozGingaFinaly battles Another Kabuto. He is subsequently captured by the mimicked Kageyama.",
        "The mascot of the Genm Corp. game DoReMiFa Beat, the character of Poppy Pipopapo was conceived by Kuroto Dan, the teenage son of Genm CEO Masamune Dan. As a Bugster, Poppy's origin is traced to the Y2K bug, which left what would be known as the Bugster Virus on the younger Dan's computer shortly following New Year's 2000. Secretly incubating the virus by infecting the young Emu Hojo with it, Kuroto Dan would arrange for its matured form to be extracted by Michihiko Zaizen ten years later, using it to execute the Zero Day incident in the following year.",
        "Sento was originally Takumi Katsuragi, an infamous researcher at Touto Institute of Advanced Matter Physics, nicknamed the \"Devil's Scientist\" who is regarded as the original creator of Project Build alongside his father Shinobu Katsuragi.\n\nEventually, Takumi discovered Soichi Isurugi's true identity as the alien entity Evolto, who came to destroy Earth just as he did with Mars, and confronted him. Just then, a man named Taro Satou arrived to respond to Takumi's job offer, but cowered in fear after seeing Stalk. Taro is killed, and the unconscious Takumi is outfitted with Taro's face and outfit, with the dead Taro now having Takumi's face and clothes. He is taken to Faust's lair and injected with Nebula Gas while Blood Stalk and Night Rogue oversaw the process.",
        "Kohtaro was born on the day of a solar eclipse, along with his stepbrother Nobuhiko Akizuki, within the same hospital. Gorgom noticed this, and both brothers were entitled heirs to their leader, the Creation King's throne. After Kohtaro's parents both died (when Kohtaro was around 3 years old) as a result of an apparent accident, Prof. Akizuki then adopted Kohtaro alongside Nobuhiko as if they were brothers. On the night of their 19th birthday, they were captured by Gorgom and were remade into cyborgs and infused with Kingstones. Kohtaro received the \"Stone of the Sun\" to become Century King Black Sun (世紀王ブラックサン Seikiō Burakku San). However before the final brainwashing Soichiro Akizuki interrupted the final stage of the process with Kohtaro barely escaping.\n\nHaving been pursued by Gorgom after his escape, Kohtaro discovers his newfound ability to turn into the a grasshopper humanoid as a result of their surgery, along with his newfound super strength and cyborg abilities.\n\nAfter receiving a letter from Soichiro, Kohtaro secretly meets with his foster father and learns the truth about his childhood. Soichiro reveals to Kohtaro that he agreed to join Gorgom in order to receive funding for his archaeological research in exchange for Kohtaro and Nobuhiko to be operated on during their 19th birthdays. When Kohtaro's father had refused to join the cult organization, Gorgom had him and Kohtaro's mother assassinated. After Prof. Akizuki is killed by five of Gorgom's Spider Mutants, Kohtaro transforms once again and takes the title of \"Kamen Rider Black.\" He then vows vengeance against Gorgom and seeks to rescue Nobuhiko from their clutches. As Black, Kohtaro gains support from Nobuhiko's younger sister, Kyoko, as well as Nobuhiko's girlfriend Katsumi. He would often be found working part-time with the two girls at the Capitola café. He would also gain allies in fight against Gorgom, such as Interpol officer Ryusuke Taki and Gorgom's own Whale Mutant."
    )

    private val raiderPhoto = intArrayOf(
        R.drawable.double_raider,
        R.drawable.skull,
        R.drawable.joker,
        R.drawable.ooo,
        R.drawable.aqua,
        R.drawable.fourze,
        R.drawable.nadeshiko,
        R.drawable.wizard,
        R.drawable.beast,
        R.drawable.mage,
        R.drawable.gaim,
        R.drawable.knuckle,
        R.drawable.kurokage,
        R.drawable.baron,
        R.drawable.drive,
        R.drawable.exaid,
        R.drawable.zio,
        R.drawable.protodrive,
        R.drawable.crossz,
        R.drawable.ghost,
        R.drawable.g3,
        R.drawable.chaser,
        R.drawable.kabuto,
        R.drawable.poppy,
        R.drawable.build,
        R.drawable.black,
    )

    val listData: ArrayList<Raider>
    get() {
        val list = arrayListOf<Raider>()
        for (position in raiderName.indices) {

            val raider = Raider()
            raider.name = raiderName[position]
            raider.gender = raiderGender[position]
            raider.motif = raiderMotif[position]
            raider.series = raiderSeries[position]
            raider.type = raiderType[position]
            raider.episode = raiderEpisode[position]
            raider.actor = raiderActor[position]
            raider.detail = raiderDetail[position]
            raider.photo = raiderPhoto[position]

            list.add(raider)
        }

        return list
    }
}